set nocompatible              " be iMproved
set encoding=utf-8

filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" Keep Plug commands between begin/end
call plug#begin()
  Plug 'gmarik/Vundle.vim'

  " Git Plugins
  Plug 'tpope/vim-fugitive'
  Plug 'airblade/vim-gitgutter'

  " Rails dev
  Plug 'tpope/vim-haml'
  Plug 'groenewege/vim-less'
  Plug 'tpope/vim-rails'
  Plug 'plasticboy/vim-markdown'
  Plug 'bruno-/vim-ruby-fold'
  Plug 'thoughtbot/vim-rspec'

  " File browser as a sidebar
  Plug 'scrooloose/nerdtree'

  " Hit Ctrl+p to open files, similar to sublime/atom/textmate
  Plug 'ctrlpvim/ctrlp.vim'

  " Colorful statusline that shows buffers along the top
  Plug 'bling/vim-airline'

  " Syntax highlighting for gui vim (macvim)
  Plug 'gosukiwi/vim-atom-dark'
  Plug 'flazz/vim-colorschemes'
  " and console vim
  Plug 'andrwb/vim-lapis256'

  " :Tab /<character to align>
  Plug 'godlygeek/tabular'

  " Adds a new adjective "s" for surrounding, e.g. cs"' will change from
  " double quotes to single quotes
  Plug 'tpope/vim-surround'

  " golang development
  Plug 'fatih/vim-go'

  " highlights trailing whitespace
  Plug 'ntpeters/vim-better-whitespace'

  " fixes pasting to not successively indent further
  Plug 'ConradIrwin/vim-bracketed-paste'

  " Session management
  Plug 'tpope/vim-obsession'
  Plug 'dhruvasagar/vim-prosession'

  " Block cursor on the command line!
  Plug 'sjl/vitality.vim'

  " <leader> c to comment or uncomment the current line/selection
  Plug 'scrooloose/nerdcommenter'

  " Rainbow parentheses
  Plug 'luochen1990/rainbow'

  " Filetype icons
  Plug 'ryanoasis/vim-devicons'

  " Fish support
  Plug 'dag/vim-fish'

  " Tom's Obvious Minimal Language support
  Plug 'cespare/vim-toml'
" All of your Plugs must be added before the following line
call plug#end()

" Line numbers
set number

" Syntax Highlighting
syntax on
set t_Co=256
set background=dark
colorscheme lapis256

" Set the rulers at 80 characters and 120 characters.
set cc=80,120
highlight ColorColumn ctermbg=DarkGray

" Set the current line to be indicated via underline in the terminal, and
" background in macvim
set cursorline

" Turn off cursor blinking in gui vim
set guicursor+=a:blinkon0

set scrolloff=8 "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

" Turn off swapfiles
set noswapfile
set nobackup
set nowb

set shiftwidth=2
set softtabstop=2
set shiftround
set expandtab         " use spaces instead of tabs when a lot of indentation is needed

" incrementally search (search as you type)
set incsearch

" automatically write the buffer when focus moves to a different one.
set autowrite

" Make backspace work in mac
set backspace=indent,eol,start

" Folding settings
set nofoldenable " turn it back on with zi
set foldmethod=indent

" .md means markdown, not modula2
autocmd BufNewFile,BufRead *.md set filetype=markdown

" When editing a file, always jump to the last known cursor position.
" Don't do it for commit messages, when the position is invalid, or when
" inside an event handler (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif


" Nerd Tree settings
" use ctrl n to toggle nerd tree
map <C-n> :NERDTreeToggle<cr>
map <C-d> :edit .
map <leader>nt :edit .<cr>

" Nerd Commenter settings
" comments always leave a space after the comment symbol
" (e.g. '# comment' or '// comment' instead of '#comment' or '//comment')
let g:NERDSpaceDelims = 1

" Always have Rainbow Parens enabled
let g:rainbow_active = 1

" use jk to exit insert mode
:imap jk <Esc>

" Buffer switching with tab
:nnoremap <Tab> :bnext<cr>
:nnoremap <S-Tab> :bprevious<cr>

" fold and unfold in normal mode with F. Fold in visual mode with F
nnoremap <silent> F @=(foldlevel('.')?'za':"\<Space>")<cr>
vnoremap F zf

" ; works just as well as : for normal mode! Saves hitting shift all the time
nnoremap ; :

" Airline related
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" Session related
" Note that sessions won't be invoked if vim is started with arguments,
" including calling `vim .`
let g:prosession_on_startup=1 " start with last session if exists
let g:prosession_dir = '~/.vim_sessions'

let mapleader = " "   " use space as the leader character

" fugitive shortcuts
noremap <leader>gs :Gstatus<cr>
noremap <leader>gc :Gcommit<cr>
noremap <leader>ga :Git add -A<cr>
noremap <leader>gl :Glog<cr>
noremap <leader>gd :Gdiff<cr>
noremap <leader>gb :Gblame<cr>
noremap <leader>gp :Gpush<cr>

" more shortcuts
noremap <leader>fs :w<cr>
noremap <leader>qq :q!<cr>

" settings for rspec
let g:rspec_runner = "os_x_iterm"
map <Leader>rf :call RunCurrentSpecFile()<cr>
map <Leader>rc :call RunNearestSpec()<cr>
map <Leader>rl :call RunLastSpec()<cr>
map <Leader>rr :call RunAllSpecs()<cr>
map <Leader>rit :! bundle exec ruby spec/integration/integration.rb<cr>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e ~/.vimrc<cr>
nmap <silent> <leader>sv :so ~/.vimrc<cr>

" Use RipGrep for all grep, including ctrl-p
if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
endif
