# This file will be loaded for interactive shells. For commands which are not specific to interactive shells,
# use .zshenv instead.

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZDOTDIR=$HOME

# Zsh, I know what I'm doing when I type rake, and it wasn't that I intended to type make. Same for mvim.
DISABLE_CORRECTION="true"

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

source ~/.dotfiles/binaries/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle rimraf/k

antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme calebmeyer/cpm-zsh-theme cpm

antigen apply

# make the terminal work like vim
bindkey -v
bindkey -M viins 'jk' vi-cmd-mode
bindkey '^r' history-incremental-search-backward

if [ -f ~/.aliases.zsh ]; then source ~/.aliases.zsh; fi
